Presentation/Nop.Web/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Nop.Core;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.Discounts;
using Nop.Core.Domain.Media;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.Vendors;
using Nop.Core.Infrastructure;
using Nop.Services.Catalog;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Customers;
using Nop.Services.Discounts;
using Nop.Services.ExportImport;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Media;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Services.Seo;
using Nop.Services.Shipping;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Catalog;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class ProductController : BaseAdminController
    {
        #region Fields

        private readonly IAclService _aclService;
        private readonly IBackInStockSubscriptionService _backInStockSubscriptionService;
        private readonly ICategoryService _categoryService;
        private readonly ICopyProductService _copyProductService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly ICustomerService _customerService;
        private readonly IDiscountService _discountService;
        private readonly IDownloadService _downloadService;
        private readonly IExportManager _exportManager;
        private readonly IImportManager _importManager;
        private readonly ILanguageService _languageService;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly IManufacturerService _manufacturerService;
        private readonly INopFileProvider _fileProvider;
        private readonly INotificationService _notificationService;
        private readonly IPdfService _pdfService;
        private readonly IPermissionService _permissionService;
        private readonly IPictureService _pictureService;
        private readonly IProductAttributeParser _productAttributeParser;
        private readonly IProductAttributeService _productAttributeService;
        private readonly IProductModelFactory _productModelFactory;
        private readonly IProductService _productService;
        private readonly IProductTagService _productTagService;
        private readonly ISettingService _settingService;
        private readonly IShippingService _shippingService;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly ISpecificationAttributeService _specificationAttributeService;
        private readonly IStoreContext _storeContext;
        private readonly IUrlRecordService _urlRecordService;
        private readonly IWorkContext _workContext;
        private readonly VendorSettings _vendorSettings;

        #endregion

        #region Ctor

        public ProductController(IAclService aclService,
            IBackInStockSubscriptionService backInStockSubscriptionService,
            ICategoryService categoryService,
            ICopyProductService copyProductService,
            ICustomerActivityService customerActivityService,
            ICustomerService customerService,
            IDiscountService discountService,
            IDownloadService downloadService,
            IExportManager exportManager,
            IImportManager importManager,
            ILanguageService languageService,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            IManufacturerService manufacturerService,
            INopFileProvider fileProvider,
            INotificationService notificationService,
            IPdfService pdfService,
            IPermissionService permissionService,
            IPictureService pictureService,
            IProductAttributeParser productAttributeParser,
            IProductAttributeService productAttributeService,
            IProductModelFactory productModelFactory,
            IProductService productService,
            IProductTagService productTagService,
            ISettingService settingService,
            IShippingService shippingService,
            IShoppingCartService shoppingCartService,
            ISpecificationAttributeService specificationAttributeService,
            IStoreContext storeContext,
            IUrlRecordService urlRecordService,
            IWorkContext workContext,
            VendorSettings vendorSettings)
        {
            _aclService = aclService;
            _backInStockSubscriptionService = backInStockSubscriptionService;
            _categoryService = categoryService;
            _copyProductService = copyProductService;
            _customerActivityService = customerActivityService;
            _customerService = customerService;
            _discountService = discountService;
            _downloadService = downloadService;
            _exportManager = exportManager;
            _importManager = importManager;
            _languageService = languageService;
            _localizationService = localizationService;
            _localizedEntityService = localizedEntityService;
            _manufacturerService = manufacturerService;
            _fileProvider = fileProvider;
            _notificationService = notificationService;
            _pdfService = pdfService;
            _permissionService = permissionService;
            _pictureService = pictureService;
            _productAttributeParser = productAttributeParser;
            _productAttributeService = productAttributeService;
            _productModelFactory = productModelFactory;
            _productService = productService;
            _productTagService = productTagService;
            _settingService = settingService;
            _shippingService = shippingService;
            _shoppingCartService = shoppingCartService;
            _specificationAttributeService = specificationAttributeService;
            _storeContext = storeContext;
            _urlRecordService = urlRecordService;
            _workContext = workContext;
            _vendorSettings = vendorSettings;
        }

        #endregion

        #region Utilities

        protected virtual void UpdateLocales(Product product, ProductModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(product,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);
                _localizedEntityService.SaveLocalizedValue(product,
                    x => x.ShortDescription,
                    localized.ShortDescription,
                    localized.LanguageId);
                _localizedEntityService.SaveLocalizedValue(product,
                    x => x.FullDescription,
                    localized.FullDescription,
                    localized.LanguageId);
                _localizedEntityService.SaveLocalizedValue(product,
                    x => x.MetaKeywords,
                    localized.MetaKeywords,
                    localized.LanguageId);
                _localizedEntityService.SaveLocalizedValue(product,
                    x => x.MetaDescription,
                    localized.MetaDescription,
                    localized.LanguageId);
                _localizedEntityService.SaveLocalizedValue(product,
                    x => x.MetaTitle,
                    localized.MetaTitle,
                    localized.LanguageId);

                //search engine name
                var seName = _urlRecordService.ValidateSeName(product, localized.SeName, localized.Name, false);
                _urlRecordService.SaveSlug(product, seName, localized.LanguageId);
            }
        }

        protected virtual void UpdateLocales(ProductTag productTag, ProductTagModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(productTag,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);

                var seName = _urlRecordService.ValidateSeName(productTag, string.Empty, localized.Name, false);
                _urlRecordService.SaveSlug(productTag, seName, localized.LanguageId);
            }
        }

        protected virtual void UpdateLocales(ProductAttributeMapping pam, ProductAttributeMappingModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(pam,
                    x => x.TextPrompt,
                    localized.TextPrompt,
                    localized.LanguageId);
                _localizedEntityService.SaveLocalizedValue(pam,
                    x => x.DefaultValue,
                    localized.DefaultValue,
                    localized.LanguageId);
            }
        }

        protected virtual void UpdateLocales(ProductAttributeValue pav, ProductAttributeValueModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(pav,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);
            }
        }

        protected virtual void UpdatePictureSeoNames(Product product)
        {
            foreach (var pp in _productService.GetProductPicturesByProductId(product.Id))

Presentation/Nop.Web/Areas/Admin/Views/Product/Edit.cshtml
@model ProductModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Products.EditProductDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Products");
}

<form asp-controller="Product" asp-action="Edit" method="post" id="product-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Catalog.Products.EditProductDetails") - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Catalog.Products.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="button" onclick="javascript:OpenWindow('@Url.RouteUrl("Product", new {SeName = Model.SeName})', 800, 600, true); return false;" class="btn bg-purple">
                <i class="fa fa-eye"></i>
                @T("Admin.Common.Preview")
            </button>
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <button type="button" name="copyproduct" class="btn bg-olive" data-toggle="modal" data-target="#copyproduct-window">
                <i class="fa fa-clone"></i>
                @T("Admin.Catalog.Products.Copy")
            </button>
            <span id="product-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="product-delete" />

@if (!Model.IsLoggedInAsVendor)
{
    //product editor settings modal
    @await Html.PartialAsync("_ProductEditorSettingsModal", Model)
}

@*copy product form*@
<div id="copyproduct-window" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="copyproduct-window-title">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="copyproduct-window-title">@T("Admin.Catalog.Products.Copy")</h4>
            </div>
            <form asp-controller="Product" asp-action="CopyProduct" method="post">
                <div class="form-horizontal">
                    <div class="modal-body">
                        <input asp-for="CopyProductModel.Id" type="hidden" />
                        <div class="form-group">
                            <div class="col-md-4">
                                <nop-label asp-for="CopyProductModel.Name" />
                            </div>
                            <div class="col-md-8">
                                <nop-editor asp-for="CopyProductModel.Name" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4">
                                <nop-label asp-for="CopyProductModel.Published" />
                            </div>
                            <div class="col-md-8">
                                <nop-editor asp-for="CopyProductModel.Published" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4">
                                <nop-label asp-for="CopyProductModel.CopyImages" />
                            </div>
                            <div class="col-md-8">
                                <nop-editor asp-for="CopyProductModel.CopyImages" />
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">
                            @T("Admin.Catalog.Products.Copy")
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Presentation/Nop.Web/Areas/Admin/Views/Product/ProductAttributeMappingEdit.cshtml
@model ProductAttributeMappingModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Products.ProductAttributes.Attributes.EditAttributeDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Products");
}

<form asp-controller="Product" asp-action="ProductAttributeMappingEdit" method="post" id="productattribute-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Catalog.Products.ProductAttributes.Attributes.EditAttributeDetails")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="Edit" asp-route-id="@Model.ProductId">@T("Admin.Catalog.Products.ProductAttributes.Attributes.BackToProduct")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="productattribute-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductAttributeMappingDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateProductAttributeMapping", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-action="ProductAttributeMappingDelete" asp-button-id="productattribute-delete" />

Presentation/Nop.Web/Areas/Admin/Views/Product/ProductAttributeValueCreatePopup.cshtml
@model ProductAttributeValueModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Products.ProductAttributes.Attributes.Values.AddNew").Text;
}
<form asp-controller="Product" asp-action="ProductAttributeValueCreatePopup"
      asp-route-productAttributeMappingId="@Context.Request.Query["productAttributeMappingId"]"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Catalog.Products.ProductAttributes.Attributes.Values.AddNew")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductAttributeValueDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateProductAttributeValue", Model)
</form>

Presentation/Nop.Web/Areas/Admin/Views/Product/TierPriceEditPopup.cshtml
@model TierPriceModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Products.TierPrices.Edit").Text;
}

<form asp-controller="Product" asp-action="TierPriceEditPopup"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Catalog.Products.TierPrices.Edit")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductTierPriceDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateTierPrice", Model)
</form>

Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.CrossSellsProducts.cshtml
@model ProductModel
<div class="panel-body">
    <p>
        @T("Admin.Catalog.Products.CrossSells.Hint")
    </p>
    @if (Model.Id > 0)
    {
    <div class="panel panel-default">

        <div class="panel-body">
            @await Html.PartialAsync("Table", new DataTablesModel
            {
                Name = "crosssellproducts-grid",
                UrlRead = new DataUrl("CrossSellProductList", "Product", new RouteValueDictionary { [nameof(Model.CrossSellProductSearchModel.ProductId)] = Model.CrossSellProductSearchModel.ProductId }),
                UrlDelete = new DataUrl("CrossSellProductDelete", "Product", null),
                Length = Model.CrossSellProductSearchModel.PageSize,
                LengthMenu = Model.CrossSellProductSearchModel.AvailablePageSizes,
                ColumnCollection = new List<ColumnProperty>
                {
                    new ColumnProperty(nameof(CrossSellProductModel.Product2Name))
                    {
                        Title = T("Admin.Catalog.Products.CrossSells.Fields.Product").Text,
                        Render = new RenderCustom("renderColumnCrossSellProductName")
                    },
                    new ColumnProperty(nameof(CrossSellProductModel.Id))
                    {
                        Title = T("Admin.Common.Delete").Text,
                        Width = "100",
                        Render = new RenderButtonRemove(T("Admin.Common.Delete").Text),
                        ClassName = NopColumnClassDefaults.Button
                    }
                }
            })
            <script>
                function renderColumnCrossSellProductName(data, type, row, meta) {
                    var textRenderer = $.fn.dataTable.render.text().display;
                    return '<a href="@Url.Content("~/Admin/Product/Edit/")' + row.ProductId2 + '">' + textRenderer(row.Product2Name) + '</a>';
                }
            </script>
        </div>
        <div class="panel-footer">
            <button type="submit" id="btnAddNewCrossSellProduct" onclick="javascript:OpenWindow('@(Url.Action("CrossSellProductAddPopup", "Product", new {productId = Model.Id, btnId = "btnRefreshCrossSellProducts", formId = "product-form"}))', 800, 800, true); return false;" class="btn btn-primary">
                @T("Admin.Catalog.Products.CrossSells.AddNew")
            </button>
            <input type="submit" id="btnRefreshCrossSellProducts" style="display: none" />
            <script>
                $(document).ready(function () {
                    $('#btnRefreshCrossSellProducts').click(function () {
                        //refresh grid
                        updateTable('#crosssellproducts-grid');

                        //return false to don't reload a page
                        return false;
                    });
                });
            </script>
        </div>
    </div>
    }
    else
    {
        <div class="panel panel-default">
            <div class="panel-body">
                @T("Admin.Catalog.Products.CrossSells.SaveBeforeEdit")
            </div>
        </div>
    }
</div>

Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.GiftCard.cshtml
@model ProductModel

@using Nop.Core.Domain.Catalog;
@using Nop.Services
<script>
    $(document).ready(function() {
        $("#@Html.IdFor(model => model.IsGiftCard)").click(toggleGiftCard);
        toggleGiftCard();
    });


    function toggleGiftCard() {
        if ($('#@Html.IdFor(model => model.IsGiftCard)').is(':checked')) {
            $('#pnlGiftCardType').show();
            $('#pnlOverriddenGiftCardAmount').show();
        } else {
            $('#pnlGiftCardType').hide();
            $('#pnlOverriddenGiftCardAmount').hide();
        }
    }
</script>
 <div class="panel-body">
        <div class="form-group">
            <div class="col-md-3">
                <nop-label asp-for="IsGiftCard" />
            </div>
            <div class="col-md-9">
                <nop-editor asp-for="IsGiftCard" />
                <span asp-validation-for="IsGiftCard"></span>
            </div>
        </div>
        <nop-nested-setting asp-for="IsGiftCard">
            <div class="form-group" id="pnlGiftCardType">
                <div class="col-md-3">
                    <nop-label asp-for="GiftCardTypeId" />
                </div>
                <div class="col-md-9">
                    <nop-select asp-for="GiftCardTypeId" asp-items="@(((GiftCardType)Model.GiftCardTypeId).ToSelectList())" />
                    <span asp-validation-for="GiftCardTypeId"></span>
                </div>
            </div>
            <div class="form-group" id="pnlOverriddenGiftCardAmount">
                <div class="col-md-3">
                    <nop-label asp-for="OverriddenGiftCardAmount" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="OverriddenGiftCardAmount" />
                    <span asp-validation-for="OverriddenGiftCardAmount"></span>
                </div>
            </div>
        </nop-nested-setting>
    </div>

Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdateProductAttributeMapping.Condition.cshtml
@model ProductAttributeMappingModel

@using System.Collections.Generic
@using Microsoft.AspNetCore.Mvc.Rendering
@using Nop.Core.Domain.Catalog
@using Nop.Services.Catalog

@if(Model.Id > 0)
{
    <script>
    $(document).ready(function() {
        $("#@Html.IdFor(model => model.ConditionModel.EnableCondition)").click(toggleEnableCondition);
        toggleEnableCondition();
    });

    function toggleEnableCondition() {
        if ($('#@Html.IdFor(model => model.ConditionModel.EnableCondition)').is(':checked')) {
            $('#pnlAttributes').show();
        } else {
            $('#pnlAttributes').hide();
        }
    }
    </script>
    <div class="panel-body">
        <p>
            @T("Admin.Catalog.Products.ProductAttributes.Attributes.Condition.Description")
        </p>

        <div class="form-group">
            <div class="col-sm-3">
                <nop-label asp-for="ConditionModel.EnableCondition" />
            </div>
            <div class="col-sm-9">
                <nop-editor asp-for="ConditionModel.EnableCondition" />
                <span asp-validation-for="ConditionModel.EnableCondition"></span>
            </div>
        </div>

        <div id="pnlAttributes" style="margin-bottom: 10px;">
            @if (Model.ConditionModel.ProductAttributes.Count > 0)
        {
            var attributesList = new List<SelectListItem>();
            foreach (var attribute in Model.ConditionModel.ProductAttributes)
            {
                attributesList.Add(new SelectListItem { Text = attribute.Name, Value = attribute.Id.ToString() });
            }
                <div class="form-group" id="pnlBasepriceUnit">
                    <div class="col-sm-3">
                        <nop-label asp-for="ConditionModel.SelectedProductAttributeId" />
                    </div>
                    <div class="col-sm-9">
                        <nop-select asp-for="ConditionModel.SelectedProductAttributeId" asp-items="@attributesList" />

                        <script>
                        $(document).ready(function() {
                            $("#@Html.IdFor(model => model.ConditionModel.SelectedProductAttributeId)")
                                .change(toggleProductAttributes);

                            toggleProductAttributes();
                        });

                        function toggleProductAttributes() {
                            var selectedProductAttributeId =
                                $("#@Html.IdFor(model => model.ConditionModel.SelectedProductAttributeId)")
                                    .val();
                            $('[id^="pnl_attribute_values_"]').hide();
                            $('#pnl_attribute_values_' + selectedProductAttributeId).show();
                        }
                        </script>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-9 col-sm-offset-3">
                        @foreach (var attribute in Model.ConditionModel.ProductAttributes)
                    {
                        var controlId = $"{NopCatalogDefaults.ProductAttributePrefix}{attribute.Id}";
                            <div id="@($"pnl_attribute_values_{attribute.Id}")">
                                @switch (attribute.AttributeControlType)
                            {
                                case AttributeControlType.DropdownList:
                                {
                                    <select name="@(controlId)" id="@(controlId)" class="form-control">
                                        @if (!attribute.IsRequired)
                                        {
                                            <option value="0">---</option>
                                        }
                                        @foreach (var attributeValue in attribute.Values)
                                        {
                                            <option selected="@attributeValue.IsPreSelected" value="@attributeValue.Id">
                                                @attributeValue.Name
                                            </option>
                                        }
                                    </select>
                                }
                                    break;
                                case AttributeControlType.RadioList:
                                case AttributeControlType.ColorSquares:
                                case AttributeControlType.ImageSquares:
                                {
                                    foreach (var attributeValue in attribute.Values)
                                    {
                                    <div class="radio">
                                        <label>
                                            <input id="@(controlId)" type="radio" name="@(controlId)" value="@attributeValue.Id" checked="@attributeValue.IsPreSelected" />
                                            @attributeValue.Name
                                        </label>
                                    </div>
                                    }
                                }
                                    break;
                                case AttributeControlType.Checkboxes:
                                {
                                    foreach (var attributeValue in attribute.Values)
                                    {
                                    <div class="radio">
                                        <label>
                                            <input id="@(controlId)" type="checkbox" name="@(controlId)" value="@attributeValue.Id" checked="@attributeValue.IsPreSelected" @(attribute.AttributeControlType == AttributeControlType.ReadonlyCheckboxes ? Html.Raw(" disabled=\"disabled\"") : null) />
                                            @attributeValue.Name
                                        </label>
                                    </div>
                                    }
                                }
                                    break;
                                case AttributeControlType.ReadonlyCheckboxes:
                                case AttributeControlType.TextBox:
                                case AttributeControlType.MultilineTextbox:
                                case AttributeControlType.Datepicker:
                                case AttributeControlType.FileUpload:
                                default:
                                    //not supported as conditions
                                    break;
                            }
                            </div>
                    }
                    </div>
                </div>
        }
        else
        {
                <div class="form-group" id="pnlBasepriceUnit">
                    <div class="col-sm-9 col-sm-offset-3">
                        No attribute exists that could be used as condition
                    </div>
                </div>
        }
        </div>
    </div>
}
else
{
    <div class="panel-body">
        @T("Admin.Catalog.Products.ProductAttributes.Attributes.Condition.SaveBeforeEdit")
    </div>
}